### ISSUE TITLE
Toggle inconsistencies

### ISSUE THREAD

**Issue by LasagnaDotGov** [bmontgomery/wemo-rest-api#4]
This API is beautiful and works well but one thing I've noticed is that a lot of the time when I use the 'toggle' command, it doesn't toggle properly.
From my observations, it seems to be about every third toggle, although this varies.

I've tried giving it a little more time between each toggle but it doesn't seem to help much.
Screencap; terminal (left), my GUI (right) -- I'll even flick you a copy of it for your troubles, if you'd like.
As you can see from the SetBinaryState actions, the toggle is inconsistent.

![image](http://puu.sh/euXJD/d109665aaf.png)

Any ideas?

**Comment by bmontgomery** [comment]
I have noticed some wonkyness with it too. I'm not sure whether the problem lies within my code, the third-party code, or whether it's just a weird thing with the switch itself. I'm sorry I don't have more help for you!

**Comment by LasagnaDotGov** [comment]
Ahh, no worries.
I appreciate the code anyway - cheers.
